name: test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code add
        uses: actions/checkout@v3
    
      - name: install node js
        uses: action/setup-node@v3
        with:
            node-version: 18
    
      - name: Install dependecncies
        run: npm ci
      - name: run tests
        run: npm test  


# name: test project
# on: push
# jobs:
#     test:
#         runs-on: windows-latest
#         steps:
#             -name:get code
#             # when you wanna use action 
#             uses:action/checkout@v3    
#             # with: - action req configuration that provided by with keyword
    